//! The on-device appliance wire protocol, generated by prost from the shared
//! `proto/dsm_anchor.proto` schema (same tooling family as the DSM backend's
//! `proto/dsm_app.proto`). Conversion helpers between the wire messages and the
//! anchor-core domain types live alongside the generated module.
//!
//! All fixed-width fields (32-byte ids/hashes) are validated on decode here,
//! since the schema carries them as plain `bytes` (the firmware compiles this
//! standalone, without the DSM custom length options).

extern crate alloc;
use alloc::vec::Vec;

use prost::Message;

use crate::root_advance::{Certificate, CounterEvidence, OfflineRelease, OwnedTransition};

/// prost-generated message types (package `dsm.anchor`).
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/dsm.anchor.rs"));
}

/// Wire-decode / conversion failures.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ProtoError {
    /// A fixed-width (32-byte) field had the wrong length, or a bounded opaque
    /// field exceeded its cap.
    BadLength,
    /// A required sub-message was absent.
    MissingField,
    /// An unknown or unspecified op selector.
    BadOp,
    /// A `slot` value outside `u16`.
    BadSlot,
    /// prost failed to decode the frame bytes.
    Decode,
}

/// Upper bound on the opaque `action_fields` (a small structured tagged-union).
pub const MAX_ACTION_FIELDS: usize = 256;
/// Upper bound on each DSM SMT leaf proof (depth ≤ 256 × 32 B + framing).
pub const MAX_LEAF_PROOF: usize = 16 * 1024;
/// Upper bound on the revealed witness public key (WOTS pk is 32 B compressed;
/// margin left for alternate witness schemes).
pub const MAX_PK_HW: usize = 4 * 1024;
/// Upper bound on the witness signature (WOTS-over-BLAKE3 σ is 2144 B; margin
/// left for alternate witness schemes).
pub const MAX_SIGMA: usize = 16 * 1024;
/// Upper bound on the authenticated L3 counter-read transcript.
pub const MAX_TRANSCRIPT: usize = 8 * 1024;

/// Validate a 32-byte field.
pub fn arr32(v: &[u8]) -> Result<[u8; 32], ProtoError> {
    if v.len() != 32 {
        return Err(ProtoError::BadLength);
    }
    let mut a = [0u8; 32];
    a.copy_from_slice(v);
    Ok(a)
}

fn bounded(v: &[u8], cap: usize) -> Result<(), ProtoError> {
    if v.len() > cap {
        Err(ProtoError::BadLength)
    } else {
        Ok(())
    }
}

// --- TransitionPackage <-> OwnedTransition (Δ) ---

impl pb::TransitionPackage {
    /// Convert the wire transition into an owned domain transition, validating
    /// every fixed-width field and bounding the opaque fields.
    pub fn to_owned_transition(&self) -> Result<OwnedTransition, ProtoError> {
        bounded(&self.action_fields, MAX_ACTION_FIELDS)?;
        bounded(&self.old_leaf_proof, MAX_LEAF_PROOF)?;
        bounded(&self.new_leaf_proof, MAX_LEAF_PROOF)?;
        Ok(OwnedTransition {
            relationship_id: arr32(&self.relationship_id)?,
            object_id: arr32(&self.object_id)?,
            sender_device_id: arr32(&self.sender_device_id)?,
            recipient_device_id: arr32(&self.recipient_device_id)?,
            prev_root: arr32(&self.prev_root)?,
            next_root: arr32(&self.next_root)?,
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            action_type: self.action_type,
            action_fields: self.action_fields.clone(),
            payload_hash: arr32(&self.payload_hash)?,
            old_leaf_proof: self.old_leaf_proof.clone(),
            new_leaf_proof: self.new_leaf_proof.clone(),
            authority_policy_hash: arr32(&self.authority_policy_hash)?,
        })
    }
}

impl OwnedTransition {
    /// Encode this transition as the wire message.
    pub fn to_pb(&self) -> pb::TransitionPackage {
        pb::TransitionPackage {
            relationship_id: self.relationship_id.to_vec(),
            object_id: self.object_id.to_vec(),
            sender_device_id: self.sender_device_id.to_vec(),
            recipient_device_id: self.recipient_device_id.to_vec(),
            prev_root: self.prev_root.to_vec(),
            next_root: self.next_root.to_vec(),
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            action_type: self.action_type,
            action_fields: self.action_fields.clone(),
            payload_hash: self.payload_hash.to_vec(),
            old_leaf_proof: self.old_leaf_proof.clone(),
            new_leaf_proof: self.new_leaf_proof.clone(),
            authority_policy_hash: self.authority_policy_hash.to_vec(),
        }
    }
}

// --- RootAdvanceCertificate <-> Certificate ---

impl pb::RootAdvanceCertificate {
    /// Decode a wire certificate, validating fixed-width fields and `slot`.
    pub fn to_cert(&self) -> Result<Certificate, ProtoError> {
        bounded(&self.pk_hw, MAX_PK_HW)?;
        bounded(&self.sigma, MAX_SIGMA)?;
        let slot = u16::try_from(self.slot).map_err(|_| ProtoError::BadSlot)?;
        Ok(Certificate {
            prev_root: arr32(&self.prev_root)?,
            next_root: arr32(&self.next_root)?,
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            transition_digest: arr32(&self.transition_digest)?,
            witness_input: arr32(&self.witness_input)?,
            pk_hash: arr32(&self.pk_hash)?,
            pk_hw: self.pk_hw.clone(),
            sigma: self.sigma.clone(),
            anchor_id: arr32(&self.anchor_id)?,
            slot,
            receiver_challenge: arr32(&self.receiver_challenge)?,
        })
    }
}

impl Certificate {
    /// Encode this certificate as the wire message.
    pub fn to_pb(&self) -> pb::RootAdvanceCertificate {
        pb::RootAdvanceCertificate {
            prev_root: self.prev_root.to_vec(),
            next_root: self.next_root.to_vec(),
            anchor_counter: self.anchor_counter,
            next_anchor_counter: self.next_anchor_counter,
            transition_digest: self.transition_digest.to_vec(),
            witness_input: self.witness_input.to_vec(),
            pk_hash: self.pk_hash.to_vec(),
            pk_hw: self.pk_hw.clone(),
            sigma: self.sigma.clone(),
            anchor_id: self.anchor_id.to_vec(),
            slot: self.slot as u32,
            receiver_challenge: self.receiver_challenge.to_vec(),
        }
    }
}

// --- CounterEvidence <-> CounterEvidence ---

impl pb::CounterEvidence {
    /// Decode wire counter evidence.
    pub fn to_evidence(&self) -> Result<CounterEvidence, ProtoError> {
        bounded(&self.verifier_transcript, MAX_TRANSCRIPT)?;
        Ok(CounterEvidence {
            anchor_id: arr32(&self.anchor_id)?,
            enrolled_counter: self.enrolled_counter,
            live_counter_claim: self.live_counter_claim,
            derived_index_claim: self.derived_index_claim,
            verifier_transcript: self.verifier_transcript.clone(),
        })
    }
}

impl CounterEvidence {
    /// Encode counter evidence as the wire message.
    pub fn to_pb(&self) -> pb::CounterEvidence {
        pb::CounterEvidence {
            anchor_id: self.anchor_id.to_vec(),
            enrolled_counter: self.enrolled_counter,
            live_counter_claim: self.live_counter_claim,
            derived_index_claim: self.derived_index_claim,
            verifier_transcript: self.verifier_transcript.clone(),
        }
    }
}

// --- OfflineRelease <-> OfflineRelease ---

impl pb::OfflineRelease {
    /// Decode a full wire release package.
    pub fn to_release(&self) -> Result<OfflineRelease, ProtoError> {
        let transition = self
            .transition
            .as_ref()
            .ok_or(ProtoError::MissingField)?
            .to_owned_transition()?;
        let cert = self.cert.as_ref().ok_or(ProtoError::MissingField)?.to_cert()?;
        let counter = self
            .counter
            .as_ref()
            .ok_or(ProtoError::MissingField)?
            .to_evidence()?;
        Ok(OfflineRelease { transition, cert, counter })
    }
}

impl OfflineRelease {
    /// Encode the release package as the wire message.
    pub fn to_pb(&self) -> pb::OfflineRelease {
        pb::OfflineRelease {
            transition: Some(self.transition.to_pb()),
            cert: Some(self.cert.to_pb()),
            counter: Some(self.counter.to_pb()),
        }
    }
}

// --- Frame codec (prost Message encode/decode) ---

/// Decode an `ApplianceRequest` frame (firmware/secure-core side).
pub fn decode_request(bytes: &[u8]) -> Result<pb::ApplianceRequest, ProtoError> {
    pb::ApplianceRequest::decode(bytes).map_err(|_| ProtoError::Decode)
}

/// Encode an `ApplianceResponse` (firmware/secure-core side).
pub fn encode_response(resp: &pb::ApplianceResponse) -> Vec<u8> {
    resp.encode_to_vec()
}

/// Encode an `ApplianceRequest` (host/transport side).
pub fn encode_request(req: &pb::ApplianceRequest) -> Vec<u8> {
    req.encode_to_vec()
}

/// Decode an `ApplianceResponse` frame (host/transport side).
pub fn decode_response(bytes: &[u8]) -> Result<pb::ApplianceResponse, ProtoError> {
    pb::ApplianceResponse::decode(bytes).map_err(|_| ProtoError::Decode)
}
